### ISSUE TITLE
create ascii2pol

### ISSUE THREAD

**Issue by mtpain** [VirtualWatershed/vw-jemez#3]
with matlab examples from @agregory65

**Comment by agregory65** [comment]
xyz=ascii2xyz('veg-out3.asc’)
save veg-out3.pol -ascii

ascii2xyz.m can be found online
Change headers in text editor

Attached .txt should have .pol extension

[veg-outex.txt](https://github.com/VirtualWatershed/vw-jemez/files/204993/veg-outex.txt)

**Comment by mtpain** [comment]
can you please provide details on how/why the headers need to be changed?
